[package]
name = "ppenc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"


[dev-dependencies]
hmac-sha256 = "1.1.3"
random-fast-rng = "0.1.1"
c2-chacha = "0.3.3"
chacha = "0.3.0"
